In [105]:
import numpy as np
import pandas as pd
import os,pickle, gc
from tqdm import tqdm
import matplotlib.pyplot as plt
pd.set_option("max_columns",300)
pd.set_option("max_rows",600)

In [2]:
train = pd.read_pickle("../pickle/train.pkl")

In [3]:
test = pd.read_pickle("../pickle/test.pkl")

In [4]:
st = pd.read_pickle("../pickle/structures.pkl")

In [45]:
st.head(50)

molecule_name  atom_index atom         x         y         z
0   dsgdb9nsd_000001           0    C -0.012698  1.085804  0.008001
1   dsgdb9nsd_000001           1    H  0.002150 -0.006031  0.001976
2   dsgdb9nsd_000001           2    H  1.011731  1.463751  0.000277
3   dsgdb9nsd_000001           3    H -0.540815  1.447527 -0.876644
4   dsgdb9nsd_000001           4    H -0.523814  1.437933  0.906397
5   dsgdb9nsd_000002           0    N -0.040426  1.024108  0.062564
6   dsgdb9nsd_000002           1    H  0.017257  0.012545 -0.027377
7   dsgdb9nsd_000002           2    H  0.915789  1.358745 -0.028758
8   dsgdb9nsd_000002           3    H -0.520278  1.343532 -0.775543
9   dsgdb9nsd_000003           0    O -0.034360  0.977540  0.007602
10  dsgdb9nsd_000003           1    H  0.064766  0.020572  0.001535
11  dsgdb9nsd_000003           2    H  0.871790  1.300792  0.000693
12  dsgdb9nsd_000004           0    C  0.599539  0.000000  1.000000
13  dsgdb9nsd_000004           1    C -0.599539  0.000000  1.000000
14  dsgdb9nsd_000004           2    H -1.661639  0.000000  1.000000
15  dsgdb9nsd_000004           3    H  1.661639  0.000000  1.000000
16  dsgdb9nsd_000005           0    C -0.013324  1.132466  0.008276
17  dsgdb9nsd_000005           1    N  0.002311 -0.019159  0.001929
18  dsgdb9nsd_000005           2    H -0.027803  2.198949  0.014154
19  dsgdb9nsd_000007           0    C -0.018704  1.525582  0.010433
20  dsgdb9nsd_000007           1    C  0.002104 -0.003882  0.001999
21  dsgdb9nsd_000007           2    H  0.994873  1.939743  0.002941
22  dsgdb9nsd_000007           3    H -0.542076  1.923611 -0.865117
23  dsgdb9nsd_000007           4    H -0.525241  1.914173  0.900024
24  dsgdb9nsd_000007           5    H  0.525487 -0.401908  0.877544
25  dsgdb9nsd_000007           6    H -1.011477 -0.418034  0.009508
26  dsgdb9nsd_000007           7    H  0.508626 -0.392470 -0.887601
27  dsgdb9nsd_000008           0    C -0.008288  1.390470 -0.005601
28  dsgdb9nsd_000008           1    O -0.007970 -0.025045  0.020306
29  dsgdb9nsd_000008           2    H  1.006583  1.815564  0.003483
30  dsgdb9nsd_000008           3    H -0.546575  1.799170 -0.873901
31  dsgdb9nsd_000008           4    H -0.522889  1.725552  0.899073
32  dsgdb9nsd_000008           5    H  0.441420 -0.333544 -0.771521
33  dsgdb9nsd_000009           0    C -0.017821  1.464358  0.010094
34  dsgdb9nsd_000009           1    C  0.002088  0.009508  0.002012
35  dsgdb9nsd_000009           2    C  0.018341 -1.191805 -0.004505
36  dsgdb9nsd_000009           3    H  0.997822  1.874253  0.002606
37  dsgdb9nsd_000009           4    H -0.542204  1.858012 -0.867212
38  dsgdb9nsd_000009           5    H -0.525333  1.848344  0.901481
39  dsgdb9nsd_000009           6    H  0.032317 -2.253148 -0.010260
40  dsgdb9nsd_000010           0    C -0.017886  1.467128  0.010113
41  dsgdb9nsd_000010           1    C  0.001738  0.010353  0.002076
42  dsgdb9nsd_000010           2    N  0.017652 -1.144529 -0.004204
43  dsgdb9nsd_000010           3    H  1.002029  1.860899  0.002454
44  dsgdb9nsd_000010           4    H -0.543988  1.844799 -0.870755
45  dsgdb9nsd_000010           5    H -0.527078  1.835182  0.904863
46  dsgdb9nsd_000011           0    C -0.002945  1.509914  0.008673
47  dsgdb9nsd_000011           1    C  0.026083  0.003276 -0.037459
48  dsgdb9nsd_000011           2    O  0.942288 -0.655070 -0.456826
49  dsgdb9nsd_000011           3    H  0.922788  1.926342 -0.391466

In [6]:
ls ../data/graph/ | head

dataset-metadata.json
dsgdb9nsd_000001.pickle
dsgdb9nsd_000002.pickle
dsgdb9nsd_000003.pickle
dsgdb9nsd_000004.pickle
dsgdb9nsd_000005.pickle
dsgdb9nsd_000007.pickle
dsgdb9nsd_000008.pickle
dsgdb9nsd_000009.pickle
dsgdb9nsd_000010.pickle


In [75]:
with open("../data/graph_v6/dsgdb9nsd_002720.pickle","rb") as f:
    data = pickle.load(f)

In [76]:
#node
np.concatenate(data[4],-1).shape

(506, 11)

In [77]:
st[st.molecule_name=="dsgdb9nsd_002720"]

molecule_name  atom_index atom         x         y         z
37824  dsgdb9nsd_002720           0    C -0.051372  1.593649 -0.043233
37825  dsgdb9nsd_002720           1    C -0.008440  0.063468 -0.014060
37826  dsgdb9nsd_002720           2    C  0.723606 -0.496589  1.210562
37827  dsgdb9nsd_002720           3    C  0.772204 -2.027719  1.248841
37828  dsgdb9nsd_002720           4    C  1.504085 -2.586356  2.473771
37829  dsgdb9nsd_002720           5    C  1.553411 -4.117780  2.513268
37830  dsgdb9nsd_002720           6    C  2.286504 -4.665952  3.740556
37831  dsgdb9nsd_002720           7    H  0.959059  2.017500 -0.057916
37832  dsgdb9nsd_002720           8    H -0.580020  1.964069 -0.927300
37833  dsgdb9nsd_002720           9    H -0.561888  1.991933  0.840842
37834  dsgdb9nsd_002720          10    H -1.032353 -0.332940 -0.035370
37835  dsgdb9nsd_002720          11    H  0.477483 -0.307558 -0.926317
37836  dsgdb9nsd_002720          12    H  1.748316 -0.099505  1.232714
37837  dsgdb9nsd_002720          13    H  0.237737 -0.125191  2.123903
37838  dsgdb9nsd_002720          14    H -0.252710 -2.424044  1.226422
37839  dsgdb9nsd_002720          15    H  1.258213 -2.398378  0.335370
37840  dsgdb9nsd_002720          16    H  2.529227 -2.190438  2.496808
37841  dsgdb9nsd_002720          17    H  1.018492 -2.216126  3.387733
37842  dsgdb9nsd_002720          18    H  0.529018 -4.512882  2.490780
37843  dsgdb9nsd_002720          19    H  2.039087 -4.487216  1.600235
37844  dsgdb9nsd_002720          20    H  2.305688 -5.760431  3.741597
37845  dsgdb9nsd_002720          21    H  3.324169 -4.314998  3.770925
37846  dsgdb9nsd_002720          22    H  1.802442 -4.340817  4.668357

In [73]:
data[4][4]

array([[ 0.0000000e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [-4.1499362e-08],
       [-1.5257275e+00],
       [-1.5247767e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [-4.1499362e-08],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [-1.9999996e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [-1.5257275e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [-4.7374973e-01],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [-1.5247767e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [-4.7574654e-01],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [ 0.0000000e+00],
       [-1.9999996e+00],


In [74]:
np.arccos(-0.524)*180/np.pi

121.60094811201677

In [93]:
data[5]

array([[ 0,  1],
       [ 0,  2],
       [ 0,  3],
       ...,
       [22, 19],
       [22, 20],
       [22, 21]], dtype=uint8)

In [95]:
node_df = pd.DataFrame(np.concatenate(data[3],-1))

In [100]:
data[3][-1].shape

(23, 11)

In [98]:
node_df.loc[[14,16,18]]

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
14  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
16  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
18  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

     15   16   17   18        19        20   21        22        23        24  \
14  0.0  0.0  0.0  1.0  0.089496  0.122665  0.0  0.026528 -0.130887  0.099327   
16  0.0  0.0  0.0  1.0  0.090199  0.124588  0.0  0.026520 -0.211916  0.179882   
18  0.0  0.0  0.0  1.0  0.091744  0.117713  0.0  0.026265 -0.040425  0.013405   

          25        26        27        28        29        30  
14 -0.003281  0.182753  0.156741  0.014498  0.186730  0.172092  
16 -0.003309  0.184131  0.158766  0.014642  0.187998  0.174207  
18 -0.003200  0.179467  0.151537  0.014065  0.183527  0.166612

In [101]:
node_df.loc[[3,4,5]]

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
3  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  2.0  0.0  0.0  0.0   
4  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  2.0  0.0  0.0  0.0   
5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  2.0  0.0  0.0  0.0   

    15   16   17   18        19        20   21        22        23        24  \
3  0.0  0.0  0.0  6.0 -0.172680 -0.247920  0.0 -0.053074  0.208196 -0.143266   
4  0.0  0.0  0.0  6.0 -0.169790 -0.248349  0.0 -0.053306  0.554732 -0.491251   
5  0.0  0.0  0.0  6.0 -0.163915 -0.214908  0.0 -0.055911 -0.306840  0.352057   

         25        26        27        28        29        30  
3  0.006645 -0.369879 -0.316964 -0.029361 -0.378232 -0.348082  
4  0.006586 -0.365486 -0.315732 -0.029155 -0.373938 -0.346355  
5  0.006267 -0.346134 -0.281599 -0.027273 -0.359591 -0.311487

In [106]:
pd.DataFrame(np.concatenate([data[5], np.concatenate(data[4], -1)], axis=1))

0     1    2    3    4    5         6         7         8         9   \
0     0.0   1.0  1.0  0.0  0.0  0.0  1.531061  0.000000  0.000000  0.000000   
1     0.0   2.0  0.0  0.0  0.0  0.0  2.557672 -1.393805  0.000000  0.000000   
2     0.0   3.0  0.0  0.0  0.0  0.0  3.932179  0.000000 -2.000000 -2.000000   
3     0.0   4.0  0.0  0.0  0.0  0.0  5.121249  0.000000  0.000000  0.000000   
4     0.0   5.0  0.0  0.0  0.0  0.0  6.459988  0.000000  0.000000  0.000000   
5     0.0   6.0  0.0  0.0  0.0  0.0  7.678888  0.000000  0.000000  0.000000   
6     0.0   7.0  1.0  0.0  0.0  0.0  1.095827  0.000000  0.000000  0.000000   
7     0.0   8.0  1.0  0.0  0.0  0.0  1.094648  0.000000  0.000000  0.000000   
8     0.0   9.0  1.0  0.0  0.0  0.0  1.095831  0.000000  0.000000  0.000000   
9     0.0  10.0  0.0  0.0  0.0  0.0  2.161974 -1.334247  0.000000  0.000000   
10    0.0  11.0  0.0  0.0  0.0  0.0  2.161969 -1.334240  0.000000  0.000000   
11    0.0  12.0  0.0  0.0  0.0  0.0  2.780950  0.000000 -0.465126 -0.465126   
12    0.0  13.0  0.0  0.0  0.0  0.0  2.781092  0.000000 -0.465458 -0.465458   
13    0.0  14.0  0.0  0.0  0.0  0.0  4.218343  0.000000  0.000000  0.000000   
14    0.0  15.0  0.0  0.0  0.0  0.0  4.218368  0.000000  0.000000  0.000000   
15    0.0  16.0  0.0  0.0  0.0  0.0  5.237424  0.000000  0.000000  0.000000   
16    0.0  17.0  0.0  0.0  0.0  0.0  5.237415  0.000000  0.000000  0.000000   
17    0.0  18.0  0.0  0.0  0.0  0.0  6.636851  0.000000  0.000000  0.000000   
18    0.0  19.0  0.0  0.0  0.0  0.0  6.636861  0.000000  0.000000  0.000000   
19    0.0  20.0  0.0  0.0  0.0  0.0  8.600183  0.000000  0.000000  0.000000   
20    0.0  21.0  0.0  0.0  0.0  0.0  7.800909  0.000000  0.000000  0.000000   
21    0.0  22.0  0.0  0.0  0.0  0.0  7.800871  0.000000  0.000000  0.000000   
22    1.0   0.0  1.0  0.0  0.0  0.0  1.531061  0.000000  0.000000  0.000000   
23    1.0   2.0  1.0  0.0  0.0  0.0  1.532728  0.000000  0.000000  0.000000   
24    1.0   3.0  0.0  0.0  0.0  0.0  2.564641 -1.400206  0.000000  0.000000   
25    1.0   4.0  0.0  0.0  0.0  0.0  3.936826  0.000000 -2.000000 -2.000000   
26    1.0   5.0  0.0  0.0  0.0  0.0  5.129288  0.000000  0.000000  0.000000   
27    1.0   6.0  0.0  0.0  0.0  0.0  6.459978  0.000000  0.000000  0.000000   
28    1.0   7.0  0.0  0.0  0.0  0.0  2.180876 -1.360965  0.000000  0.000000   
29    1.0   8.0  0.0  0.0  0.0  0.0  2.184719 -1.367128  0.000000  0.000000   
30    1.0   9.0  0.0  0.0  0.0  0.0  2.180857 -1.360936  0.000000  0.000000   
31    1.0  10.0  1.0  0.0  0.0  0.0  1.098177  0.000000  0.000000  0.000000   
32    1.0  11.0  1.0  0.0  0.0  0.0  1.098178  0.000000  0.000000  0.000000   
33    1.0  12.0  0.0  0.0  0.0  0.0  2.160369 -1.329351  0.000000  0.000000   
34    1.0  13.0  0.0  0.0  0.0  0.0  2.160343 -1.329317  0.000000  0.000000   
35    1.0  14.0  0.0  0.0  0.0  0.0  2.790372  0.000000 -0.465835 -0.465835   
36    1.0  15.0  0.0  0.0  0.0  0.0  2.790554  0.000000 -0.466161 -0.466161   
37    1.0  16.0  0.0  0.0  0.0  0.0  4.221884  0.000000  0.000000  0.000000   
38    1.0  17.0  0.0  0.0  0.0  0.0  4.221768  0.000000  0.000000  0.000000   
39    1.0  18.0  0.0  0.0  0.0  0.0  5.244622  0.000000  0.000000  0.000000   
40    1.0  19.0  0.0  0.0  0.0  0.0  5.244715  0.000000  0.000000  0.000000   
41    1.0  20.0  0.0  0.0  0.0  0.0  7.306021  0.000000  0.000000  0.000000   
42    1.0  21.0  0.0  0.0  0.0  0.0  6.678574  0.000000  0.000000  0.000000   
43    1.0  22.0  0.0  0.0  0.0  0.0  6.678476  0.000000  0.000000  0.000000   
44    2.0   0.0  0.0  0.0  0.0  0.0  2.557672 -1.393805  0.000000  0.000000   
45    2.0   1.0  1.0  0.0  0.0  0.0  1.532728  0.000000  0.000000  0.000000   
46    2.0   3.0  1.0  0.0  0.0  0.0  1.532380  0.000000  0.000000  0.000000   
47    2.0   4.0  0.0  0.0  0.0  0.0  2.563586 -1.399373  0.000000  0.000000   
48    2.0   5.0  0.0  0.0  0.0  0.0  3.936832  0.000000 -2.000000 -2.000000   
49    2.0   6.0  0.0  0.0  0.0  0.0  5.121241  0.000000  

In [87]:
tmp = np.concatenate([data[5], data[4][2]], axis=1)
tmp[tmp[:,2]!=0]

array([[ 0.       ,  2.       , -1.3938049],
       [ 0.       , 10.       , -1.3342475],
       [ 0.       , 11.       , -1.3342402],
       [ 1.       ,  3.       , -1.4002057],
       [ 1.       ,  7.       , -1.3609649],
       [ 1.       ,  8.       , -1.3671281],
       [ 1.       ,  9.       , -1.3609358],
       [ 1.       , 12.       , -1.3293514],
       [ 1.       , 13.       , -1.3293175],
       [ 2.       ,  0.       , -1.3938049],
       [ 2.       ,  4.       , -1.3993733],
       [ 2.       , 10.       , -1.3289189],
       [ 2.       , 11.       , -1.3289297],
       [ 2.       , 14.       , -1.3302133],
       [ 2.       , 15.       , -1.3302261],
       [ 3.       ,  1.       , -1.4002057],
       [ 3.       ,  5.       , -1.400215 ],
       [ 3.       , 12.       , -1.3308911],
       [ 3.       , 13.       , -1.3308724],
       [ 3.       , 16.       , -1.3308835],
       [ 3.       , 17.       , -1.3308791],
       [ 4.       ,  2.       , -1.3993733],
       [ 4

In [9]:
data[4][0][:100]

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0,

In [46]:
data[4][0][100:200]

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0,

In [47]:
data[4][0][200:300]

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0,

In [48]:
data[4][0][300:]

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [10]:
data[6]

(array([5581, 5582, 5583, 5584, 5585, 5586, 5587, 5588, 5589, 5590, 5591,
        5592, 5593, 5594, 5595, 5596, 5597, 5598, 5599, 5600, 5601, 5602,
        5603, 5604, 5605, 5606, 5607, 5608, 5609, 5610, 5611, 5612, 5613,
        5614, 5615, 5616, 5617, 5618, 5619, 5620, 5621, 5622, 5623, 5624,
        5625, 5626, 5627, 5628, 5629]),
 array([[ 8.25219e+01,  1.56383e-01,  9.14480e-01,  6.65949e-01],
        [-2.31922e+00,  9.79620e-02,  9.24730e-02, -9.07080e-02],
        [ 2.85637e+00, -2.51380e-02, -4.20410e-02,  4.31400e-02],
        [ 2.85634e+00, -2.51380e-02, -4.20410e-02,  4.31390e-02],
        [-1.16235e+01,  3.64356e-01,  2.21272e+00, -2.46157e+00],
        [-1.16236e+01,  3.64357e-01,  2.21271e+00, -2.46156e+00],
        [ 1.20774e+01,  2.70340e-02,  1.95160e+00, -2.76175e+00],
        [ 7.99916e+01,  1.69406e-01,  9.49564e-01,  6.24583e-01],
        [-1.95624e+00,  8.09940e-02,  9.63430e-02, -1.11250e-01],
        [ 1.07498e+00, -1.38030e-02, -1.85800e-03, -1.03980e-02],
    

In [12]:
data[5].shape

(182, 2)

In [20]:
data[3]

[array([[0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0]], dtype=uint8), array([[0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0]], dtype=uint8), array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0]], dtype=uint8), array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0]], dtype=uint8), array([[0, 0, 1],
        [0, 0, 1],
        [0

In [28]:
data[3][0]

array([[0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]], dtype=uint8)

In [33]:
np.argmax(data[3][0],axis=1)

array([1, 1, 1, 1, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.argwhere(data[3][0])[:,1]

array([1, 1, 1, 1, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
data[4][1].shape

(182, 1)

In [13]:
data[6][2].shape

(49, 2)

In [178]:
data_st = st[st.molecule_name == data[0]]
data_st = data_st.merge(data_st, on="molecule_name", how="left",suffixes=("_0","_1"))
data_st = data_st[data_st.atom_index_0 != data_st.atom_index_1].reset_index(drop=True)
data_st["dist"] = np.linalg.norm(data_st[["x_0","y_0","z_0"]].values - data_st[["x_1","y_1","z_1"]].values, axis=1)

In [192]:
data_st

molecule_name  atom_index_0 atom_0       x_0       y_0       z_0  \
0    dsgdb9nsd_000306             0      C -0.460258  1.460440 -0.066967   
1    dsgdb9nsd_000306             0      C -0.460258  1.460440 -0.066967   
2    dsgdb9nsd_000306             0      C -0.460258  1.460440 -0.066967   
3    dsgdb9nsd_000306             0      C -0.460258  1.460440 -0.066967   
4    dsgdb9nsd_000306             0      C -0.460258  1.460440 -0.066967   
5    dsgdb9nsd_000306             0      C -0.460258  1.460440 -0.066967   
6    dsgdb9nsd_000306             0      C -0.460258  1.460440 -0.066967   
7    dsgdb9nsd_000306             0      C -0.460258  1.460440 -0.066967   
8    dsgdb9nsd_000306             0      C -0.460258  1.460440 -0.066967   
9    dsgdb9nsd_000306             0      C -0.460258  1.460440 -0.066967   
10   dsgdb9nsd_000306             0      C -0.460258  1.460440 -0.066967   
11   dsgdb9nsd_000306             0      C -0.460258  1.460440 -0.066967   
12   dsgdb9nsd_000306             0      C -0.460258  1.460440 -0.066967   
13   dsgdb9nsd_000306             1      C  0.106879  0.051912  0.031743   
14   dsgdb9nsd_000306             1      C  0.106879  0.051912  0.031743   
15   dsgdb9nsd_000306             1      C  0.106879  0.051912  0.031743   
16   dsgdb9nsd_000306             1      C  0.106879  0.051912  0.031743   
17   dsgdb9nsd_000306             1      C  0.106879  0.051912  0.031743   
18   dsgdb9nsd_000306             1      C  0.106879  0.051912  0.031743   
19   dsgdb9nsd_000306             1      C  0.106879  0.051912  0.031743   
20   dsgdb9nsd_000306             1      C  0.106879  0.051912  0.031743   
21   dsgdb9nsd_000306             1      C  0.106879  0.051912  0.031743   
22   dsgdb9nsd_000306             1      C  0.106879  0.051912  0.031743   
23   dsgdb9nsd_000306             1      C  0.106879  0.051912  0.031743   
24   dsgdb9nsd_000306             1      C  0.106879  0.051912  0.031743   
25   dsgdb9nsd_000306             1      C  0.106879  0.051912  0.031743   
26   dsgdb9nsd_000306             2      C  1.335029 -0.297657 -0.870766   
27   dsgdb9nsd_000306             2      C  1.335029 -0.297657 -0.870766   
28   dsgdb9nsd_000306             2      C  1.335029 -0.297657 -0.870766   
29   dsgdb9nsd_000306             2      C  1.335029 -0.297657 -0.870766   
..                ...           ...    ...       ...       ...       ...   
152  dsgdb9nsd_000306            11      H  1.863463  0.590931 -1.236394   
153  dsgdb9nsd_000306            11      H  1.863463  0.590931 -1.236394   
154  dsgdb9nsd_000306            11      H  1.863463  0.590931 -1.236394   
155  dsgdb9nsd_000306            11      H  1.863463  0.590931 -1.236394   
156  dsgdb9nsd_000306            12      H  1.308945  0.583011  1.836529   
157  dsgdb9nsd_000306            12      H  1.308945  0.583011  1.836529   
158  dsgdb9nsd_000306            12      H  1.308945  0.583011  1.836529   
159  dsgdb9nsd_000306            12      H  1.308945  0.583011  1.836529   
160  dsgdb9nsd_000306            12      H  1.308945  0.583011  1.836529   
161  dsgdb9nsd_000306            12      H  1.308945  0.583011  1.836529   
162  dsgdb9nsd_000306            12      H  1.308945  0.583011  1.836529   
163  dsgdb9nsd_000306            12      H  1.308945  0.583011  1.836529   
164  dsgdb9nsd_000306            12      H  1.308945  0.583011  1.836529   
165  dsgdb9nsd_000306            12      H  1.308945  0.583011  1.836529   
166  dsgdb9nsd_000306            12      H  1.308945  0.583011  1.836529   
167  dsgdb9nsd_000306            12      H  1.308945  0.583011  1.836529   
168  dsgdb9nsd_000306            12      H  1.308945  0.583011  1.836529   
169  dsgdb9nsd_000306            13      H  0.512941 -0.991779  2.037055   
170  dsgdb9nsd_000306            13      H  0.512941 -0.991779  2.037055   
171  dsgdb9nsd_000306            13      H  0.512941 -0.991779  2.037055   
172  dsgdb9nsd_000306            13      H  0.512941 -0.

In [196]:
np.unique(data_st[(data_st["dist"]<2)&(data_st.atom_index_0.isin([0,3]))]["atom_index_1"].tolist() + [0,3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [197]:
atoms = data_st["atom_index_0"].unique()
atoms

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [199]:
np.isin(atoms, [0,1,3,4,5,6])

array([ True,  True, False,  True,  True,  True,  True, False, False,
       False, False, False, False, False])

In [180]:
data_st.dist < 3

0       True
1       True
2      False
3      False
4       True
5       True
6       True
7       True
8       True
9      False
10      True
11      True
12     False
13      True
14      True
15      True
16     False
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
       ...  
152    False
153     True
154    False
155    False
156     True
157     True
158     True
159     True
160    False
161     True
162     True
163    False
164     True
165    False
166    False
167    False
168     True
169    False
170     True
171    False
172     True
173     True
174     True
175    False
176    False
177    False
178     True
179    False
180    False
181     True
Name: dist, Length: 182, dtype: bool

In [174]:
#距離がcutoff以下のペアを抽出
near_pair = data_st[data_st.dist < 3][["atom_index_0","atom_index_1"]].values
# couplingが0,1だったときの対象エッジ
near_pair[np.isin(near_pair,[0,1]).any(axis=1)]

array([[ 0,  1],
       [ 0,  2],
       [ 0,  5],
       [ 0,  6],
       [ 0,  7],
       [ 0,  8],
       [ 0,  9],
       [ 0, 11],
       [ 0, 12],
       [ 1,  0],
       [ 1,  2],
       [ 1,  3],
       [ 1,  5],
       [ 1,  6],
       [ 1,  7],
       [ 1,  8],
       [ 1,  9],
       [ 1, 10],
       [ 1, 11],
       [ 1, 12],
       [ 1, 13],
       [ 2,  0],
       [ 2,  1],
       [ 3,  1],
       [ 5,  0],
       [ 5,  1],
       [ 6,  0],
       [ 6,  1],
       [ 7,  0],
       [ 7,  1],
       [ 8,  0],
       [ 8,  1],
       [ 9,  0],
       [ 9,  1],
       [10,  1],
       [11,  0],
       [11,  1],
       [12,  0],
       [12,  1],
       [13,  1]])

In [176]:
np.unique(near_pair[np.isin(near_pair,[0,1]).any(axis=1)])

array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [175]:
for arr in near_pair:
    print(arr)

[0 1]
[0 2]
[0 5]
[0 6]
[0 7]
[0 8]
[0 9]
[ 0 11]
[ 0 12]
[1 0]
[1 2]
[1 3]
[1 5]
[1 6]
[1 7]
[1 8]
[1 9]
[ 1 10]
[ 1 11]
[ 1 12]
[ 1 13]
[2 0]
[2 1]
[2 3]
[2 4]
[2 5]
[2 6]
[2 7]
[2 9]
[ 2 10]
[ 2 11]
[ 2 12]
[3 1]
[3 2]
[3 4]
[3 5]
[3 9]
[ 3 10]
[ 3 11]
[ 3 12]
[ 3 13]
[4 2]
[4 3]
[4 5]
[ 4 10]
[ 4 13]
[5 0]
[5 1]
[5 2]
[5 3]
[5 4]
[5 6]
[5 8]
[5 9]
[ 5 11]
[ 5 12]
[ 5 13]
[6 0]
[6 1]
[6 2]
[6 5]
[6 7]
[6 8]
[ 6 11]
[ 6 12]
[7 0]
[7 1]
[7 2]
[7 6]
[7 8]
[7 9]
[ 7 11]
[8 0]
[8 1]
[8 5]
[8 6]
[8 7]
[8 9]
[ 8 12]
[9 0]
[9 1]
[9 2]
[9 3]
[9 5]
[9 7]
[9 8]
[ 9 10]
[ 9 13]
[10  1]
[10  2]
[10  3]
[10  4]
[10  9]
[10 11]
[11  0]
[11  1]
[11  2]
[11  3]
[11  5]
[11  6]
[11  7]
[11 10]
[12  0]
[12  1]
[12  2]
[12  3]
[12  5]
[12  6]
[12  8]
[12 13]
[13  1]
[13  3]
[13  4]
[13  5]
[13  9]
[13 12]
